version: "3"
services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - ./:/code
    working_dir: /code
    command: npm run start
    ports:
      - "8080:8080"
    tty: true
